//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        public int id_indent { get; set; }
        public int id_preparation { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual indent indent { get; set; }
        public virtual preparation preparation { get; set; }
    }
}
