//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class preparation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public preparation()
        {
            this.order_details = new HashSet<order_details>();
        }
    
        public int id_preparation { get; set; }
        public string producer { get; set; }
        public string release_form { get; set; }
        public string day_dosage { get; set; }
        public string drug_name { get; set; }
        public int price { get; set; }
        public Nullable<int> amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
    }
}
